Multiple reference speeds: different velocity frames for each species (#13)
* Add `c0ref`, `u0ref`, `n0ref` to `species_info`.

* Test `test_rosenbluth_potential_grid_conversion()` for developing grid converter for Rosenbluth potentials.

* Save parameters Inn_vec for recalculation of multipole expansion in grid converter for Rosenbluth potentials. Introduce data structure to hold multipole expansion data for delta_f_multipole case.

* Use type dispatch to reduce number of separate functions for multipole boundary data logic.

* Pass only float values of vpa and vperp into analytical functions for Maxwellian quantities, rather than struct and integer index.

* Change line ending to LF.

* Refactor multipole moment and expansion calculation to use dispatch to determine whether to use multipole or delta f multipole expansion at the lowest levels.

* An analytical calculation of the Inm moments used in the multipole expansion, and tests of the expected behaviour of the calculation of the stored Inm due to calling `calculate_rosenbluth_potentials_via_elliptic_solve!()`.

* Remove unused mass parameter from `calculate_rosenbluth_potentials_via_elliptic_solve!`. This can be removed because the thermal speed in the reference units can be computed without knowing the species mass input parameter, unlike the pressure.

* Ensure that `boundary_data_option=direct_integration` fails at compile time, e.g.,
```
julia> FokkerPlanckTestsBase.test_rosenbluth_potential_grid_conversion(rtol=5.0e-6,boundary_data_option=FokkerPlanck.direct_integration,print_to_screen=true)
ERROR: MethodError: no method matching rosenbluth_potential_to_other_grid!(::FokkerPlanck.fokker_planck_calculus.GLabel, ::Matrix{…}, ::Matrix{…}, ::Nothing, ::FokkerPlanck.coordinates.finite_element_coordinate, ::FokkerPlanck.coordinates.finite_element_coordinate, ::Float64, ::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::Int64)
The function `rosenbluth_potential_to_other_grid!` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  rosenbluth_potential_to_other_grid!(::FokkerPlanck.fokker_planck_calculus.AbstractRosenbluthPotentialLabel, ::AbstractMatrix{Float64}, ::AbstractMatrix{Float64}, ::Union{FokkerPlanck.fokker_planck_calculus.delta_f_multipole_moments, Vector{Float64}}, ::FokkerPlanck.coordinates.finite_element_coordinate, ::FokkerPlanck.coordinates.finite_element_coordinate, ::Float64, ::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::Int64)
   @ FokkerPlanck ~/excalibur-mk/FokkerPlanck/src/fokker_planck_calculus.jl:3985
```

* Ensure that calculate_analytical_Maxwellian_multipole_expansion_moments!() is also tested for the `delta_f_multipole_moments` input type.

* Test for development of multi-reference velocity collision operator.

* Extend multi-reference velocity implementation to `multi_species_operator_option == single_assembly_per_species`.

* Add c0ref, u0ref, n0ref as inputs to backward Euler test scripts.

* Extend end-of-step corrections to support multiple reference velocities.

* Extend ImplicitCollisionsTestBase.jl diagnostics to multiple reference velocities.